import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {ChangeEvent, useState, MouseEvent} from 'react'
import {log} from 'console'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [result, setResult] = useState('')
    const [messageInput, setMessageInput] = useState(
        'what are some of your legendary catchphrases?'
    )
    const [character, setCharacter] = useState('Homer Simpson')
    const onSubmit = async (event: React.MouseEvent<HTMLElement>) => {
        event.preventDefault()
        try {
            const response = await fetch('/api/generate', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({message: messageInput, character: character}),
            })

            const data = await response.json()
            if (response.status !== 200) {
                throw (
                    data.error ||
                    new Error(`Request failed with status ${response.status}`)
                )
            }

            setResult(data.result)
            setMessageInput('')
        } catch (error: any) {
            // Consider implementing your own error handling logic here
            console.error(error)
            alert(error.message)
        }
    }

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setMessageInput(event.target.value)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <h1>Ask me anything!</h1>
                <div className={styles.description}>{result}</div>
                <input onChange={handleChange}></input>
                <button onClick={onSubmit}>Test button</button>
            </main>
        </>
    )
}
